<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Migrations\20260902082041_AddRefreshTokens.cs" />
    <Compile Remove="Migrations\20260902082041_AddRefreshTokens.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyProfile.Core\CompanyProfile.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
